<a href="https://colab.research.google.com/github/Jaseem1911/DataPreprocessing/blob/main/Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# reading csv file
csvFile= pd.read_csv('/content/drive/MyDrive/IRIS.csv')
# displaying the contents of the csv file
print(csvFile)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
csvFile['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
csvFile[['sepal_length','sepal_width']]

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [ ]:
csvFile.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
csvFile[csvFile['sepal_length']<6].head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
csvFile['species'].head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object

In [ ]:
csvFile['new']=csvFile['sepal_length']+csvFile['petal_length']

In [ ]:
csvFile

,sepal_length,sepal_width,petal_length,petal_width,species,new
0,5.1,3.5,1.4,0.2,Iris-setosa,6.5
1,4.9,3.0,1.4,0.2,Iris-setosa,6.3
2,4.7,3.2,1.3,0.2,Iris-setosa,6.0
3,4.6,3.1,1.5,0.2,Iris-setosa,6.1
4,5.0,3.6,1.4,0.2,Iris-setosa,6.4
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,11.9
146,6.3,2.5,5.0,1.9,Iris-virginica,11.3
147,6.5,3.0,5.2,2.0,Iris-virginica,11.7
148,6.2,3.4,5.4,2.3,Iris-virginica,11.6
149,5.9,3.0,5.1,1.8,Iris-virginica,11.0